[19-Dec-2015 10:20:06 America/New_York] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', NULL, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'root', NULL, Array)
#2 /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', NULL, Array)
#3 /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect()
#4 /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabas in /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[19-Dec-2015 11:20:18 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/siacolwe/public_html/m/app/cache/prod/appProdUrlMatcher.php:66
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/UrlMatcher.php(112): appProdUrlMatcher->match('/')
#1 /home/siacolwe/public_html/m/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(256): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/siacolwe/public_html/m/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php(137): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/siacolwe/public_h in /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[19-Dec-2015 11:22:27 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Routing\Exception\ResourceNotFoundException' in /home/siacolwe/public_html/m/app/cache/prod/appProdUrlMatcher.php:66
Stack trace:
#0 /home/siacolwe/public_html/m/app/cache/prod/classes.php(1419): appProdUrlMatcher->match('/')
#1 /home/siacolwe/public_html/m/app/cache/prod/classes.php(1282): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#2 /home/siacolwe/public_html/m/app/cache/prod/classes.php(2478): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
#3 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher))
#4 /home/siacolwe/public_html/m/app/cache/prod/classes.php(2266): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Obje in /home/siacolwe/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103
[21-Dec-2015 15:42:53 America/New_York] PHP Fatal error:  Class 'Doctrine\Bundle\DoctrineBundle\ConnectionFactory' not found in /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php on line 294
[21-Dec-2015 15:42:54 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ClassNotFoundException' with message 'Attempted to load class "ConnectionFactory" from namespace "Doctrine\Bundle\DoctrineBundle".
Did you forget a "use" statement for another namespace?' in /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php:294
Stack trace:
#0 {main}

Next exception 'Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException' with message 'Circular reference detected for service "security.authentication.manager", path: "security.firewall.map.context.default -> security.authentication.manager -> security.user.provider.concrete.our_db_provider -> doctrine.orm.default_entity_manager -> doctrine.dbal.default_connection -> doctrine.dbal.connection_factory -> twig.controller.exception -> twig -> security.authorization_checker".' in /home/siacolwe/public_html/m/app/bootstrap.php.cache:2129
Stack trace:
#0 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(734): Symfony\Component\De in /home/siacolwe/public_html/m/app/bootstrap.php.cache on line 2129
[21-Dec-2015 15:44:25 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:25 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:25 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:25 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:44:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:29 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:44:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:44:29 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:52:24 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:24 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:24 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:24 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:52:28 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:28 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:28 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:28 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:52:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:29 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:29 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:52:30 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:30 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:30 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:30 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:52:33 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:33 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:33 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:33 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:52:49 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:49 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:49 America/New_York] PHP Warning:  file_get_contents(C:\xampp\htdocs\siacolweb-servicio\app\config\parameters_db\environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 29
[21-Dec-2015 15:52:49 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 70 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(70): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 15:53:03 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[21-Dec-2015 15:53:03 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[21-Dec-2015 15:53:03 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment18.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[21-Dec-2015 15:53:03 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[21-Dec-2015 16:27:29 America/New_York] PHP Fatal error:  Call to a member function getMessageData() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/SecurityController.php on line 39
[21-Dec-2015 16:27:50 America/New_York] PHP Fatal error:  Call to a member function getMessageData() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/SecurityController.php on line 23
[21-Dec-2015 16:27:51 America/New_York] PHP Fatal error:  Call to a member function getMessageData() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/SecurityController.php on line 23
[21-Dec-2015 16:31:07 America/New_York] PHP Fatal error:  Call to a member function getProfalum() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 25
[22-Dec-2015 11:11:22 America/New_York] PHP Fatal error:  Call to a member function getProfalum() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 25
[22-Dec-2015 11:27:32 America/New_York] PHP Fatal error:  Call to a member function getProfalum() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 25
[28-Dec-2015 09:04:49 America/New_York] PHP Fatal error:  Call to a member function getProfalum() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 25
[28-Dec-2015 10:27:09 America/New_York] PHP Warning:  Missing argument 1 for Symfony\Component\HttpFoundation\Request::getUriForPath(), called in /home/siacolwe/public_html/m/src/AppBundle/EventListener/EnvironmentListener.php on line 25 and defined in /home/siacolwe/public_html/m/app/bootstrap.php.cache on line 869
[28-Dec-2015 10:33:21 America/New_York] PHP Fatal error:  Call to a member function getProfalum() on a non-object in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 25
[28-Dec-2015 11:25:09 America/New_York] PHP Parse error:  syntax error, unexpected 'T' (T_STRING) in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 81
[28-Dec-2015 11:25:19 America/New_York] PHP Parse error:  syntax error, unexpected 'T' (T_STRING) in /home/siacolwe/public_html/m/src/AppBundle/Controller/ConsultarNotasController.php on line 81
[16-Jan-2016 18:46:44 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:46:44 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:46:44 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:46:44 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[16-Jan-2016 18:46:46 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:46:46 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:46:46 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:46:46 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[16-Jan-2016 18:47:08 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:08 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:08 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:08 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[16-Jan-2016 18:47:27 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:27 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:27 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:27 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[16-Jan-2016 18:47:30 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:30 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:30 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:30 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
[16-Jan-2016 18:47:31 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:31 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:31 America/New_York] PHP Warning:  file_get_contents(/home/siacolwe/public_html/m/app/config/parameters_db/environment15.yml): failed to open stream: No such file or directory in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 30
[16-Jan-2016 18:47:31 America/New_York] PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Doctrine\Bundle\DoctrineBundle\ConnectionFactory::createConnection() must be of the type array, null given, called in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php on line 71 and defined' in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:51
Stack trace:
#0 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php(51): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 1 pass...', '/home/siacolwe/...', 51, Array)
#1 /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/CustomConnectionFactory.php(71): Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection(NULL, Object(Doctrine\DBAL\Configuration), Object(Symfony\Bridge\Doctrine\ContainerAwareEventManager), Array)
#2 /home/siacolwe/public_html/m/app/cache/prod/appProdProjectContainer.php(300): in /home/siacolwe/public_html/m/vendor/doctrine/doctrine-bundle/ConnectionFactory.php on line 51
